<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
					xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
					xmlns:tns="http://services.gsisws/"
					xmlns:par="http://parameters.services.gsisws/"
					xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
					xmlns:xsd="http://www.w3.org/2001/XMLSchema"
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
					xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
					xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
					name="GsisService"
					targetNamespace="http://services.gsisws/">
  
	<wsp:Policy wsu:Id="USNToken"
		xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
		xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
					<wsp:Policy>
						<sp:UsernameToken 
							sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
						</sp:UsernameToken>
					</wsp:Policy>
				</sp:SupportingTokens>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsdl:types>
		<xsd:schema targetNamespace="http://services.gsisws/">
			<xsd:import namespace="http://parameters.services.gsisws/" schemaLocation="gsismodel.xsd"/>
		</xsd:schema>    
	</wsdl:types>
	<wsdl:message name="queryByTaxIdRequest">
		<wsdl:part element="par:queryByTaxIdRequest" name="parameters"/>
	</wsdl:message> 
	<wsdl:message name="queryByTaxIdResponse">
		<wsdl:part element="par:queryByTaxIdResponse" name="parameters"/>
	</wsdl:message> 
	<wsdl:portType name="GsisService">
		<wsdl:operation name="queryByTaxId">
			<wsdl:input message="tns:queryByTaxIdRequest"/>
			<wsdl:output message="tns:queryByTaxIdResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GsisServiceSOAP" type="tns:GsisService">		
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsp:PolicyReference URI="#USNToken" wsdl:required="true"/>
		<wsdl:operation name="queryByTaxId">
			<soap:operation soapAction="queryByTaxId"/>
				<wsdl:input>
					<soap:body use="literal"/>
				</wsdl:input>
				<wsdl:output>
					<soap:body use="literal"/>
				</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GsisService">
		<wsdl:documentation>GSIS Web Service</wsdl:documentation>
		<wsdl:port binding="tns:GsisServiceSOAP" name="GsisServiceSOAP">
			<soap:address location="http://localhost:8080/gsisws/services/GsisService"/>			
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
